### ISSUE TITLE
Request : Add support for group invite

### ISSUE THREAD

**Issue by BbayuGt** [open-wa/whatsapp-button#443]
Make a Group invite support will be better. Example
```html
<whatsapp-button group="EC6fNhC5mjZBKyW9jxxxxx" label="Join our group"></whatsapp-button>```

**Comment by smashah** [comment]
@BbayuGt with the latest version you can set the group invite code:

https://open-wa.github.io/whatsapp-button/?path=/story/whatsappbutton--group-invite

```html
<whatsapp-button invitecode="EC6fNhC5mjZBKyW9jxxxxx" label="Join our group"></whatsapp-button>
```
